-- ============================================
-- PASO 1: ELIMINAR TABLA EXISTENTE (si existe)
-- ============================================
-- Ejecuta esto primero para limpiar
drop table if exists public.bf_black_friday_2025 cascade;

-- ============================================
-- PASO 2: CREAR TABLA NUEVA
-- ============================================
create table public.bf_black_friday_2025 (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text,
  email text,
  whatsapp text,
  empresa text,
  rol text,
  presupuesto text,
  tipo_proyecto text,
  descripcion text,
  metodo_pago text,
  estado text default 'pendiente',
  conversation_log jsonb  -- IMPORTANTE: JSONB, no TEXT
);

-- ============================================
-- PASO 3: CONFIGURAR ROW LEVEL SECURITY (RLS)
-- ============================================
alter table public.bf_black_friday_2025 enable row level security;

-- Política para permitir INSERT a usuarios anónimos
create policy "Enable insert for anon users"
on public.bf_black_friday_2025
for insert
to anon
with check (true);

-- Política para permitir SELECT a usuarios anónimos (opcional, para debugging)
create policy "Enable select for anon users"
on public.bf_black_friday_2025
for select
to anon
using (true);

-- ============================================
-- VERIFICACIÓN
-- ============================================
-- Ejecuta esto para verificar que la tabla se creó correctamente:
-- SELECT * FROM public.bf_black_friday_2025 LIMIT 1;
